/**
 * ============================================================================
 * Purpose:
 * This utility is responsible for generating JSON Web Tokens (JWT) after a
 * user successfully authenticates. Instead of duplicating JWT generation logic
 * inside multiple controllers or services, we centralize it here.
 
 * Workflow:
 * 1. Receives an authenticated user object.
 * 2. Extracts only the information that should be stored inside the token.
 * 3. Signs the payload using JWT_SECRET.
 * 4. Returns the generated token.
 
 * Why this file exists:
 * - Avoids code duplication.
 * - Makes token generation consistent throughout the application.
 * - Simplifies future modifications (expiry time, payload, algorithm, etc.).
 
 * Security Notes:
 * - Never include sensitive information such as passwords in the JWT payload.
 * - The token should only contain information required for identifying the user.
 * ============================================================================
 */

const jwt = require("jsonwebtoken");

const generateToken = (user) => {
  return jwt.sign(
    {
      id: user._id,
      username: user.username,
      email: user.email,
    },
    process.env.JWT_SECRET,
    {
      expiresIn: "7d",
    }
  );
};

module.exports = generateToken;

/**
 * ---------------------------------------------------------------------------
   About the fuction : jwt.sign(payload, secretOrPrivateKey, options)
 * ---------------------------------------------------------------------------
 * Purpose:
 * Creates a digitally signed JSON Web Token (JWT) containing the provided
 * payload. The token is later sent by the client with every authenticated
 * request to prove the user's identity.
 *
 * Parameters:
 *
 * 1. payload
 *    The data to be embedded inside the token.
 *    This information is NOT encrypted—it is only signed. Anyone with the
 *    token can decode and read this data, but cannot modify it without
 *    invalidating the signature.
 *
 *    We include only non-sensitive information:
 *      - user id
 *      - username
 *      - email
 *
 *    Never store passwords or confidential information inside the payload.
 *
 * 2. process.env.JWT_SECRET
 *    A secret key used to digitally sign the token.
 *    During verification, the same secret is required to confirm that the
 *    token was generated by our server and has not been tampered with.
 *
 *    If the secret changes, all previously issued tokens become invalid.
 *
 * 3. options
 *    Additional configuration for the generated token.
 *
 *    expiresIn: "7d"
 *        Specifies the token's validity period.
 *        After 7 days, the token expires and the user must authenticate again.
 * ---------------------------------------------------------------------------
 */
